name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Run Tests
        run: ./tests/run_test.sh

      - name: Notify Discord On Success
        if: success()
        run: |
          curl -s -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d '{
            "embeds": [
              {
                "title": "✅ Testing Successful!",
                "description": "All tests have passed!",
                "color": 3066993,
                "fields": [
                  { "name": "Branch", "value": "'"${GITHUB_REF##*/}"'", "inline": true },
                  { "name": "Commit", "value": "[`'"${GITHUB_SHA::7}"'`](https://github.com/'"${GITHUB_REPOSITORY}"'/commit/'"${GITHUB_SHA}"')", "inline": true },
                  { "name": "Author", "value": "'"${GITHUB_ACTOR}"'", "inline": true }
                ],
                "footer": { "text": "Testing Notification" },
                "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
              }
            ]
          }'
      - name: Notify Discord On Failure
        if: failure()
        run: |
          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "content": "<@&1402893883150569584>",
            "embeds": [
              {
                "title": "❌ Testing Failed!",
                "description": "🚨 Some tests have failed.\n[📄 View Logs]('"https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"')",
                "color": 16711680,
                "fields": [
                  { "name": "Branch", "value": "'"${GITHUB_REF##*/}"'", "inline": true },
                  { "name": "Commit", "value": "[`'"${GITHUB_SHA::7}"'`](https://github.com/'"${GITHUB_REPOSITORY}"'/commit/'"${GITHUB_SHA}"')", "inline": true },
                  { "name": "Author", "value": "'"${GITHUB_ACTOR}"'", "inline": true }
                ],
                "footer": { "text": "Testing Notification" },
                "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
              }
            ]
          }'
